#pragma once

void can_handler__manage_mia_10hz(void);
void can_handler__handle_all_incoming_messages(void);
void can_handler__transmit_sensor_button_message_10hz(void);
void can_handler__transmit_sensor_accmtr_message_10hz(void);